experiment:
  version: 0.3.1
  dataset: cat_dbpedia_movielens_small
  align_side_with_train: False
  data_config:
#    strategy: dataset
#    dataset_path: ../data/cat_dbpedia_movielens_small/ratings.tsv
    strategy: fixed
    train_path: ../data/cat_dbpedia_movielens_small/splitting/0/train.tsv
#    validation_path: ../data/{0}/valid.dat
    test_path: ../data/cat_dbpedia_movielens_small/splitting/0/test.tsv
    side_information:
      - dataloader: ChainedKG
        map: ../data/cat_dbpedia_movielens_small/map2.tsv
        features: ../data/cat_dbpedia_movielens_small/features2.tsv
        properties: ../data/cat_dbpedia_movielens_small/properties.conf
        threshold: 30
#  prefiltering:
#    strategy: user_average # Not applied in the paper experiments
#  splitting:
#    save_on_disk: True
#    save_folder: ../data/cat_dbpedia_movielens_small/splitting/
#    test_splitting:
#        strategy: temporal_hold_out
#        test_ratio: 0.2
#    validation_splitting:
#        strategy: temporal_hold_out
#        test_ratio: 0.2
  top_k: 10
  evaluation:
    cutoffs: [10, 5]
    simple_metrics: [nDCG,Precision,ItemCoverage,EPC,Gini]
    relevance_threshold: 1
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    VSM:
      meta:
        verbose: True
        save_recs: False
      loader: ChainedKG
      user_profile: tfidf
      item_profile: tfidf
      similarity: dot
    Random:
      meta:
        verbose: True
        save_recs: False
      seed: 42
    external.MostPop:
      meta:
        verbose: True
        save_recs: False
        validation_metric: nDCG@10
#    ItemKNN:
#      meta:
#        verbose: True
#        save_recs: True
#        validation_metric: nDCG@10
#      neighbors: [50, 70, 100]
#      similarity: [cosine, euclidean]
#      implementation: standard
    AttributeItemKNN:
      meta:
        verbose: True
        save_recs: False
        validation_metric: nDCG@10
      loader: ChainedKG
      neighbors: 10
      similarity: cosine